{"uuid": "79dbc64f-9139-4a2c-af20-94d17b7eb4a5", "children": ["a0f6ecc5-edc0-408f-a9da-51e7ba448a4c"], "befores": [{"name": "action", "status": "passed", "start": 1647948310310, "stop": 1647948310311}], "afters": [{"name": "action::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"/usr/local/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/likunyu/project/521-uiautomation/base/conftest_android.py\", line 56, in action\n    element_action.driver.quit()\n  File \"/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"/usr/local/lib/python3.9/site-packages/appium/webdriver/errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647948311406, "stop": 1647948311420}], "start": 1647948310310, "stop": 1647948311420}